export const MAX_WHITE_CARDS = 10;
export const STAGE_DRAW_BLACK_CARD = "STAGE_DRAW_BLACK_CARD";
export const STAGE_WHITE_CARDS_SELECTION = "STAGE_WHITE_CARDS_SELECTION";
export const STAGE_CHOOSE_WINNER = "STAGE_CHOOSE_WINNER";
