export const ROUNDS_QUANTITY = 5;
export const MAX_WHITE_CARDS = 5;
export const STAGE_DRAW_BLACK_CARD = "STAGE_DRAW_BLACK_CARD";
export const STAGE_WHITE_CARDS_SELECTION = "STAGE_WHITE_CARDS_SELECTION";
export const STAGE_CHOOSING_WINNER = "STAGE_CHOOSING_WINNER";
export const STAGE_CHOSEN_WINNER = "STAGE_CHOSEN_WINNER";
export const COUNT_DOWN_SECONDS = 5;
